function vec = autosimBuildSemanticFeatures(windObs, droneObs, tagObs, semantic, cfg)
    try
        vec = autosim_ontology_engine('build_features', windObs, droneObs, tagObs, semantic, cfg);
        if isnumeric(vec)
            return;
        end
    catch
    end

    vec = [ ...
        autosimClampNaN(autosimVizField(semantic, 'r_body', autosimVizField(semantic, 'wind_body_risk', 0.0)), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 'r_gust', autosimVizField(semantic, 'wind_gust_risk', 0.0)), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_tilt', 0.0), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_descent', 0.0), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_lateral', 0.0), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_visual', autosimVizField(semantic, 'visual_enc', 0.0)), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_align', autosimVizField(semantic, 'alignment_enc', 0.0)), 0.0), ...
        autosimClampNaN(autosimVizField(semantic, 's_context', 0.0), 0.0) ...
    ];
    vec = max(0.0, min(1.0, vec));
end


