function cfg = autosimGetModelTypeConfig(baseConfig, modelType)
% autosimGetModelTypeConfig
% Returns model configuration based on model type: "aii_only" or "ontology_ai"
%
% Usage:
%   cfg = autosimGetModelTypeConfig(baseConfig, 'aii_only')
%   cfg = autosimGetModelTypeConfig(baseConfig, 'ontology_ai')

if nargin < 2 || isempty(modelType)
    modelType = 'ontology_ai';
end

cfg = baseConfig;
modelType = lower(string(modelType));

% Sensor-only AI model: uses only core sensor and control features
sensor_only_features = [ ...
    "mean_wind_speed", "max_wind_speed", "wind_velocity", "wind_acceleration", ...
    "mean_abs_roll_deg", "mean_abs_pitch_deg", "mean_abs_vz", "max_abs_vz", ...
    "mean_tag_error", "max_tag_error", "stability_std_z", "stability_std_vz", ...
    "mean_imu_ang_vel", "max_imu_ang_vel", "mean_imu_lin_acc", "max_imu_lin_acc" ...
];

% Extended features for wind body forces and arm imbalance
extended_sensor_features = [ ...
    sensor_only_features, ...
    "wind_velocity_x", "wind_velocity_y", "wind_acceleration_x", "wind_acceleration_y", ...
    "max_contact_force", "arm_force_imbalance", ...
    "final_altitude", "final_abs_speed" ...
];

% Ontology features (physics-aware semantic/risk encodings)
ontology_features = [ ...
    "landing_feasibility", "mean_wind_risk_raw", ...
    "mean_wind_body_risk", "mean_wind_gust_risk", "mean_wind_dir_change_risk", ...
    "min_thrust_margin_n", "navigation_instability", "trajectory_quality", ...
    "wind_hazardous_ratio", "mean_estimation_uncertainty", ...
    "wind_risk_enc", "alignment_enc", "visual_enc", ...
    "relation_wind_control", "relation_visual_alignment", "relation_estimation_conflict" ...
];

% Ontology-derived temporal patterns and decomposed risk channels
ontology_derived_features = [ ...
    "onto_wind_condition", "onto_gust", "onto_temporal_pattern", ...
    "onto_drone_state", "onto_tag_observation", ...
    "onto_wind_body_risk", "onto_wind_accel_risk", "onto_wind_dir_change_risk" ...
];

% Combined ontology+AI model: uses sensor features + ontology features + ontology-derived features
ontology_ai_combined_features = [ ...
    extended_sensor_features, ...
    ontology_features, ...
    ontology_derived_features ...
];
ontology_ai_combined_features = unique(ontology_ai_combined_features, 'stable');

cfg.model_type_selected = modelType;

switch modelType
    case "aii_only"
        % AI-only model: sensor and basic control features without ontology
        cfg.model.feature_names = sensor_only_features;
        cfg.model.schema_version = "decision_sensor_single_ai_v1";
        cfg.model.include_ontology_features = false;
        cfg.model.description = "AI-only model using core sensor and control features";
        
    case "ontology_ai"
        % Ontology+AI model: sensor features + ontology encodings + ontology-derived features
        cfg.model.feature_names = ontology_ai_combined_features;
        cfg.model.schema_version = "decision_ontology_ai_combined_v2_physics";
        cfg.model.include_ontology_features = true;
        cfg.model.description = "Ontology+AI model using sensor features + ontology encodings + ontology-derived features";
        
    otherwise
        error('autosimGetModelTypeConfig:InvalidModelType', ...
            'Invalid model type: %s. Use "aii_only" or "ontology_ai".', modelType);
end

% Store feature lists for reference and validation
cfg.model.sensor_only_features = sensor_only_features;
cfg.model.extended_sensor_features = extended_sensor_features;
cfg.model.ontology_features = ontology_features;
cfg.model.ontology_derived_features = ontology_derived_features;

fprintf('[autosimGetModelTypeConfig] Selected model type: %s (%s)\n', ...
    modelType, cfg.model.description);
fprintf('[autosimGetModelTypeConfig] Feature count: %d\n', numel(cfg.model.feature_names));
end
